server:
  port: 8202

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_cmn?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123

  profiles:
    active: dev

  # 返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # redis配置
  redis:
    host: 192.168.198.129
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1 # 最大阻塞等待时间，负数表示没有
        min-idle: 0

#  application:
#    name: server-hosp


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml



