server:
  port: 8206

spring:
  application:
    name: service-order
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis配置
  redis:
    host: 192.168.198.129
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        max-wait: -1 # 最大阻塞等待时间，负数表示没有
        min-idle: 0


  rabbitmq:
    host: 192.168.198.129
    port: 15672
    username: admin
    password: 123


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

weixin:
  pay:
    appid: wx74862e0dfcf69954 #关联公众号appid
    partner: 1558950191 #商户号
    partnerkey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb #商户key
  cert: D:\\Users\\Administrator\\java代码\\yygh_parent\\service\\service-order\\src\\main\\resources\\cert


