server:
  port: 8201

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123

  profiles:
    active: dev

  # 返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#  application:
#    name: server-hosp


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

