server:
  port: 8201

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_hosp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123

  # 开发环境
  profiles:
    active: dev

  # 返回json的全局时间格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # mongodb地址
  data:
    mongodb:
      host: 192.168.198.129
      port: 27017
      database: yygh_hosp

  # 微服务模块名称
  application:
    name: server-hosp

  # 配置nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    host: 192.168.198.129
    port: 15672
    username: admin
    password: 123


management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露监控端点


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

